version: "3.4"

services:
  streamer-spotliht-db:
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=streamer-spotliht-db
      - POSTGRES_PASSWORD=secret-password
      - POSTGRES_USER=streamer-spotliht
